### ISSUE TITLE
Nice !!

### ISSUE THREAD

**Issue by FGRibreau** [santosh79/remixdb#1]
Awesome work @santosh79!

I'm sharing RemixDb in [RedisWeekly](http://redisweekly.com), did you tried RemixDB against [Redsmin](https://redsmin.com)? 

If so, would you like to put Redsmin as an officiel GUI for RemixDB inside your Readme? We offer real-time monitoring and alerting on top of classic GUI features :)

**Comment by santosh79** [comment]
Thanks @FGRibreau! :) Appreciate your putting it in RedisWeekly. I have still not completed implementing all of the feature sets (sorted sets/pub sub etc.). Will hopefully have it somewhat feature set complete in 3 weeks.

Best,
Santosh

**Comment by FGRibreau** [comment]
:+1:
