### ISSUE TITLE
Atomicity

### ISSUE THREAD

**Issue by ramonsnir** [santosh79/remixdb#2]
How do you ensure atomicity of execution with commands like getset, setnx, etc.?

**Comment by santosh79** [comment]
The Actor model makes this very easy. For example, the `rpoplpush` needs to be atomic, i.e. the item should not be in both lists at the same time and also should be there in one of the lists.

Here is the implementation: https://github.com/santosh79/remixdb/blob/master/lib/list.ex#L99

`getset` is a lot easier, here's the code: https://github.com/santosh79/remixdb/blob/master/lib/string.ex#L67

**Comment by ramonsnir** [comment]
And how to you plan to keep that atomicity for multiple key operations? Actor.update inside Actor.update, to achieve locking on all relevant keys?

**Comment by santosh79** [comment]
`rpoplpush` is a great example of achieving atomicity across multiple keys. We `rpop` from a list and `lpush` onto another. And that is being done now. The trick is to do these inside a `handle_*` callback.

**Comment by ramonsnir** [comment]
Aren't you worried that this strategy will limit parallelism when introducing lua scripts, that potentially take dozens or hundreds of milliseconds to execute?

**Comment by santosh79** [comment]
I haven't thought about scripting quite yet. I have some homework to do to
figure out how to integrate that in. Even so, a long running Lua script
will impact Redis just as much. So the end-user experience would remain the
same....

**Comment by ramonsnir** [comment]
No doubt that Redis has as issue with this, but this might be a good edge for remix! 😄

**Comment by santosh79** [comment]
True, in RemixDB I could look at not locking the "entire" database, just
the key-values that are impacted by the script. It's hard but possible.
